 **Pytorch로 Softmax Regression 구현**

In [91]:
#학습 데이터 생성
import torch

x_train=torch.FloatTensor([[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]])
y_train=torch.FloatTensor([[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]])

#w,b 초기화
#optimizer 생성하기

w=torch.zeros(4,3,requires_grad=True)
b=torch.zeros(1,3,requires_grad=True)

optimizer=torch.optim.Adam([w,b],lr=0.1)

#반복횟수 설정
#가설 및 비용 설정하기
for epoch in range(3001):
  hypothesis=torch.softmax(torch.mm(x_train,w)+b,dim=1) #  hypothesis=torch.softmax(torch.mm(x_train,w)+b,dim=1)
  cost=-torch.mean(torch.sum(y_train*torch.log(hypothesis),dim=1)) # cost=-torch.mean(torch.sum(y_train*torch.log(hypothesis),dim=1))


  #optimizer 를 이용한 경사 계산 및 w, b 업데이트

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  #학습이 잘 되었는지 확인하기 위한 내용 출력
  if epoch%300 ==0:
    print("epoch: {},cost: {:.6f}".format(epoch,cost.item()))


# x가 [1,11,10,9],[1,3,4,3],[1,1,0,1]일 때, y값은?
print("\nx가 [1,11,10,9],[1,3,4,3],[1,1,0,1]일 때, y값은?\n")
w.requires_grad_(False)
b.requires_grad_(False)

x_test=torch.FloatTensor([[1,11,10,9],[1,3,4,3],[1,1,0,1]])
test_all=torch.softmax(torch.mm(x_test,w)+b,dim=1)
print(test_all)
print(torch.argmax(test_all,dim=1))

epoch: 0,cost: 1.098612
epoch: 300,cost: 0.105262
epoch: 600,cost: 0.042634
epoch: 900,cost: 0.023111
epoch: 1200,cost: 0.014479
epoch: 1500,cost: 0.009879
epoch: 1800,cost: 0.007124
epoch: 2100,cost: 0.005338
epoch: 2400,cost: 0.004113
epoch: 2700,cost: 0.003236
epoch: 3000,cost: 0.002588

x가 [1,11,10,9],[1,3,4,3],[1,1,0,1]일 때, y값은?

tensor([[1.0000e+00, 5.5165e-19, 7.0151e-38],
        [1.4800e-02, 7.4294e-01, 2.4226e-01],
        [1.2256e-33, 9.0835e-12, 1.0000e+00]])
tensor([0, 1, 2])


**조금 더 깔끔하게 Softmax** ->cross_entropy를 사용

In [90]:
#학습 데이터 생성
#torch.nn.functional을 F라는 이름으로 사용하겠다고 선언 


import torch
import torch.nn.functional as F


x_train=torch.FloatTensor([[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]])
y_train=torch.LongTensor([2,2,2,1,1,1,0,0]) #y_train수정

#w,b 초기화
#optimizer 생성하기

w=torch.zeros(4,3,requires_grad=True)
b=torch.zeros(1,3,requires_grad=True)

optimizer=torch.optim.Adam([w,b],lr=0.1)

#반복횟수 설정
#가설 및 비용 수정하기
for epoch in range(3001):
  z=torch.mm(x_train,w)+b
  cost=F.cross_entropy(z,y_train) #F.cross_entropy = softmax+ cross_entropy




  #optimizer 를 이용한 경사 계산 및 w, b 업데이트

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  #학습이 잘 되었는지 확인하기 위한 내용 출력
  if epoch%300 ==0:
    print("epoch: {},cost: {:.6f}".format(epoch,cost.item()))



# x가 [1,11,10,9],[1,3,4,3],[1,1,0,1]일 때, y값은?
print("\nx가 [1,11,10,9],[1,3,4,3],[1,1,0,1]일 때, y값은?\n")
w.requires_grad_(False)
b.requires_grad_(False)

x_test=torch.FloatTensor([[1,11,10,9],[1,3,4,3],[1,1,0,1]])
test_all=torch.softmax(torch.mm(x_test,w)+b,dim=1)
print(test_all)
print(torch.argmax(test_all,dim=1))

epoch: 0,cost: 1.098612
epoch: 300,cost: 0.105263
epoch: 600,cost: 0.042634
epoch: 900,cost: 0.023111
epoch: 1200,cost: 0.014479
epoch: 1500,cost: 0.009879
epoch: 1800,cost: 0.007124
epoch: 2100,cost: 0.005338
epoch: 2400,cost: 0.004113
epoch: 2700,cost: 0.003236
epoch: 3000,cost: 0.002588

x가 [1,11,10,9],[1,3,4,3],[1,1,0,1]일 때, y값은?

tensor([[1.0000e+00, 5.5164e-19, 7.0151e-38],
        [1.4799e-02, 7.4294e-01, 2.4226e-01],
        [1.2256e-33, 9.0836e-12, 1.0000e+00]])
tensor([0, 1, 2])


In [88]:
#w와 b를 nn.Linear로 대체하는 부분


import torch
import torch.nn.functional as F #torch.nn.functional을 F라는 이름으로 사용하겠다고 선언 
import torch.nn as nn

x_train=torch.FloatTensor([[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]])
y_train=torch.LongTensor([2,2,2,1,1,1,0,0]) #y_train수정

#w와 b를 nn.Linear로 대체하기
model=nn.Linear(4,3)
optimizer=torch.optim.Adam(model.parameters(),lr=1)

#반복횟수 설정
#가설 및 비용 수정하기
for epoch in range(3001):
  z=model(x_train)
  cost=F.cross_entropy(z,y_train) #F.cross_entropy = softmax+ cross_entropy




  #optimizer 를 이용한 경사 계산 및 w, b 업데이트

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  #학습이 잘 되었는지 확인하기 위한 내용 출력
  if epoch%300 ==0:
    print("epoch: {},cost: {:.6f}".format(epoch,cost.item()))



epoch: 0,cost: 2.340644
epoch: 300,cost: 0.028330
epoch: 600,cost: 0.011371
epoch: 900,cost: 0.006160
epoch: 1200,cost: 0.003869
epoch: 1500,cost: 0.002647
epoch: 1800,cost: 0.001914
epoch: 2100,cost: 0.001437
epoch: 2400,cost: 0.001109
epoch: 2700,cost: 0.000874
epoch: 3000,cost: 0.000700


Softmax Regression with Sklearn

In [89]:
#y에 두 종류 이상의 값이 있을 경우 softmax regression 실행


import numpy as np
from sklearn.linear_model import LogisticRegression

x_train=np.array([[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]])

#y에 0,1,2등 둘 이상의 class가 존재 => softmax regression
y_train=np.array([2,2,2,1,1,1,0,0])

logistic=LogisticRegression() #모델 생성
logistic.fit(x_train,y_train) #학습

#값예측
pred=logistic.predict([[1,11,10,9],[1,3,4,3],[1,1,0,1]]) #test case
print(pred) #출력

[0 2 2]
